In [1]:
import pandas as pd

In [2]:
data_vac = pd.read_csv('COVID-19_Vaccinations_in_the_United_States_Jurisdiction_20240111.csv')
data_vac

,Date,MMWR_week,Location,Distributed,Distributed_Janssen,Distributed_Moderna,Distributed_Pfizer,Distributed_Novavax,Distributed_Unk_Manuf,Dist_Per_100K,...,Dist_Bivalent_PFR,Dist_Bivalent_MOD,Bivalent_Booster_5Plus,Bivalent_Booster_5Plus_Pop_Pct,Bivalent_Booster_12Plus,Bivalent_Booster_12Plus_Pop_Pct,Bivalent_Booster_18Plus,Bivalent_Booster_18Plus_Pop_Pct,Bivalent_Booster_65Plus,Bivalent_Booster_65Plus_Pop_Pct
0,05/10/2023,19,NE,5481710,152400,1647380,2905630,7400.0,0,283379,...,575480.0,193420.0,340508.0,18.9,332054.0,20.5,319161.0,21.9,151146.0,48.4
1,05/10/2023,19,LA,10282120,330500,3807980,5164550,10100.0,0,221178,...,640590.0,328400.0,359506.0,8.3,356199.0,9.1,349934.0,9.8,184844.0,24.9
2,05/10/2023,19,GA,28727475,869100,9763000,14773655,43400.0,0,270569,...,2255000.0,1023320.0,1126791.0,11.3,1103841.0,12.3,1067468.0,13.2,476297.0,31.4
3,05/10/2023,19,WY,1281755,49300,490040,585605,3700.0,0,221466,...,102510.0,50600.0,65920.0,12.1,64919.0,13.2,63244.0,14.2,34832.0,35.1
4,05/10/2023,19,CO,17769135,501900,5402640,9029715,43600.0,0,308560,...,2033760.0,757520.0,1268501.0,23.4,1229981.0,24.9,1176686.0,26.2,462990.0,55.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
38483,12/13/2020,51,AS,3900,0,0,0,NaN,0,7003,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
38484,12/13/2020,51,VI,975,0,0,0,NaN,0,931,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
38485,12/13/2020,51,MP,4875,0,0,0,NaN,0,8570,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
38486,12/13/2020,51,US,13650,0,0,0,NaN,0,4,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
38487,12/13/2020,51,GU,3900,0,0,0,NaN,0,2353,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [3]:
data_death = pd.read_csv('deaths_with_abbs.csv')
data_death

,Data as of,Start Date,End Date,Group,Year,Month,MMWR Week,Week Ending Date,State,COVID-19 Deaths,Total Deaths,Percent of Expected Deaths,Pneumonia Deaths,Pneumonia and COVID-19 Deaths,Influenza Deaths,"Pneumonia, Influenza, or COVID-19 Deaths",Footnote,Location
0,01/11/2024,12/29/2019,01/04/2020,By Week,2019/2020,NaN,1.0,01/04/2020,United States,0.0,60170.0,98.0,4111.0,0.0,434.0,4545.0,NaN,NaN
1,01/11/2024,01/05/2020,01/11/2020,By Week,2020,NaN,2.0,01/11/2020,United States,1.0,60734.0,97.0,4153.0,1.0,475.0,4628.0,NaN,NaN
2,01/11/2024,01/12/2020,01/18/2020,By Week,2020,NaN,3.0,01/18/2020,United States,2.0,59362.0,98.0,4066.0,2.0,468.0,4534.0,NaN,NaN
3,01/11/2024,01/19/2020,01/25/2020,By Week,2020,NaN,4.0,01/25/2020,United States,3.0,59162.0,99.0,3915.0,0.0,500.0,4418.0,NaN,NaN
4,01/11/2024,01/26/2020,02/01/2020,By Week,2020,NaN,5.0,02/01/2020,United States,0.0,58834.0,99.0,3818.0,0.0,481.0,4299.0,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
14305,01/11/2024,01/01/2020,01/06/2024,By Total,NaN,NaN,NaN,NaN,Washington,15510.0,265746.0,NaN,20905.0,9023.0,590.0,27950.0,NaN,WA
14306,01/11/2024,01/01/2020,01/06/2024,By Total,NaN,NaN,NaN,NaN,West Virginia,8548.0,105264.0,NaN,11252.0,4361.0,214.0,15640.0,NaN,WV
14307,01/11/2024,01/01/2020,01/06/2024,By Total,NaN,NaN,NaN,NaN,Wisconsin,17500.0,240385.0,NaN,15338.0,6176.0,449.0,27075.0,NaN,WI
14308,01/11/2024,01/01/2020,01/06/2024,By Total,NaN,NaN,NaN,NaN,Wyoming,1903.0,22099.0,NaN,1948.0,988.0,41.0,2902.0,NaN,WY
14309,01/11/2024,01/01/2020,01/06/2024,By Total,NaN,NaN,NaN,NaN,Puerto Rico,6582.0,134740.0,NaN,18785.0,4525.0,379.0,21175.0,NaN,NaN

In [46]:
print(data_vac.head())

         Date  MMWR_week Location  Distributed  Distributed_Janssen  \
0  05/10/2023         19       NE      5481710               152400
1  05/10/2023         19       LA     10282120               330500
2  05/10/2023         19       GA     28727475               869100
3  05/10/2023         19       WY      1281755                49300
4  05/10/2023         19       CO     17769135               501900

   Distributed_Moderna  Distributed_Pfizer  Distributed_Novavax  \
0              1647380             2905630               7400.0
1              3807980             5164550              10100.0
2              9763000            14773655              43400.0
3               490040              585605               3700.0
4              5402640             9029715              43600.0

   Distributed_Unk_Manuf  Dist_Per_100K  ...  Dist_Bivalent_MOD  \
0                      0         283379  ...           193420.0
1                      0         221178  ...           328400.0
2                      0         270569  ...          1023320.0
3                      0         221466  ...            50600.0
4                      0         308560  ...           757520.0

   Bivalent_Booster_5Plus  Bivalent_Booster_5Plus_Pop_Pct  \
0                340508.0                            18.9
1                359506.0                             8.3
2               1126791.0                            11.3
3                 65920.0                            12.1
4               1268501.0                            23.4

   Bivalent_Booster_12Plus  Bivalent_Booster_12Plus_Pop_Pct  \
0                 332054.0                             20.5
1                 356199.0                              9.1
2                1103841.0                             12.3
3                  64919.0                             13.2
4                1229981.0                             24.9

   Bivalent_Booster_18Plus  Bivalent_Booster_18Plus_Pop_Pct  \
0                 319161.0                             21.9
1                 349934.0                              9.8
2                1067468.0                             13.2
3                  63244.0                             14.2
4                1176686.0                             26.2

   Bivalent_Booster_65Plus  Bivalent_Booster_65Plus_Pop_Pct  year
0                 151146.0                             48.4  2023
1                 184844.0                             24.9  2023
2                 476297.0                             31.4  2023
3                  34832.0                             35.1  2023
4                 462990.0                             55.0  2023

[5 rows x 110 columns]

In [47]:
print(data_death.head())

   Data as of  Start Date    End Date    Group  Year  Month  MMWR Week  \
1  01/11/2024  01/05/2020  01/11/2020  By Week  2020    NaN        2.0
2  01/11/2024  01/12/2020  01/18/2020  By Week  2020    NaN        3.0
3  01/11/2024  01/19/2020  01/25/2020  By Week  2020    NaN        4.0
4  01/11/2024  01/26/2020  02/01/2020  By Week  2020    NaN        5.0
5  01/11/2024  02/02/2020  02/08/2020  By Week  2020    NaN        6.0

  Week Ending Date          State  COVID-19 Deaths  Total Deaths  \
1       01/11/2020  United States              1.0       60734.0
2       01/18/2020  United States              2.0       59362.0
3       01/25/2020  United States              3.0       59162.0
4       02/01/2020  United States              0.0       58834.0
5       02/08/2020  United States              4.0       59482.0

   Percent of Expected Deaths  Pneumonia Deaths  \
1                        97.0            4153.0
2                        98.0            4066.0
3                        99.0            3915.0
4                        99.0            3818.0
5                       100.0            3823.0

   Pneumonia and COVID-19 Deaths  Influenza Deaths  \
1                            1.0             475.0
2                            2.0             468.0
3                            0.0             500.0
4                            0.0             481.0
5                            1.0             520.0

   Pneumonia, Influenza, or COVID-19 Deaths Footnote Location
1                                    4628.0      NaN      NaN
2                                    4534.0      NaN      NaN
3                                    4418.0      NaN      NaN
4                                    4299.0      NaN      NaN
5                                    4346.0      NaN      NaN

In [37]:
# creating a new column for year in order to merge our two datasets based on year
data_vac['year'] = pd.DatetimeIndex(data_vac['Date']).year

In [38]:
data_vac.dtypes

Date                                object
MMWR_week                            int64
Location                            object
Distributed                          int64
Distributed_Janssen                  int64
                                    ...
Bivalent_Booster_18Plus            float64
Bivalent_Booster_18Plus_Pop_Pct    float64
Bivalent_Booster_65Plus            float64
Bivalent_Booster_65Plus_Pop_Pct    float64
year                                 int64
Length: 110, dtype: object

In [39]:
data_death.dtypes

Data as of                                   object
Start Date                                   object
End Date                                     object
Group                                        object
Year                                         object
Month                                       float64
MMWR Week                                   float64
Week Ending Date                             object
State                                        object
COVID-19 Deaths                             float64
Total Deaths                                float64
Percent of Expected Deaths                  float64
Pneumonia Deaths                            float64
Pneumonia and COVID-19 Deaths               float64
Influenza Deaths                            float64
Pneumonia, Influenza, or COVID-19 Deaths    float64
Footnote                                     object
Location                                     object
dtype: object

In [40]:
# dropping the rows that are formatted like 2019/2020 for example
data_death = data_death[data_death["Year"].str.contains("/")==False]

In [41]:
# converting year column to an integer 
data_death['Year'] = data_death['Year'].astype(int)

<ipython-input-41-f52baac55b0b>:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data_death['Year'] = data_death['Year'].astype(int)

In [42]:
data_death.dtypes

Data as of                                   object
Start Date                                   object
End Date                                     object
Group                                        object
Year                                          int64
Month                                       float64
MMWR Week                                   float64
Week Ending Date                             object
State                                        object
COVID-19 Deaths                             float64
Total Deaths                                float64
Percent of Expected Deaths                  float64
Pneumonia Deaths                            float64
Pneumonia and COVID-19 Deaths               float64
Influenza Deaths                            float64
Pneumonia, Influenza, or COVID-19 Deaths    float64
Footnote                                     object
Location                                     object
dtype: object

We have prepared our two datasets to be merged. We will be merging on three columns so we ensured that the column types and relevant information aligned.

In [43]:
combined_data = data_vac.merge(data_death, left_on = ['MMWR_week', 'Location', 'year'], 
                                   right_on = ['MMWR Week', 'Location', 'Year'],
                                   how = 'left')
combined_data.shape

(38488, 127)

In [44]:
combined_data = combined_data[combined_data['MMWR_week'] <= 19]
covid_deaths = combined_data[~combined_data['COVID-19 Deaths'].isna()]

In [45]:
covid_deaths.to_csv('covid_deaths.csv')

Changing Columns Integer to String

In [53]:
# data_death
data_death['State'] = data_death['State'].astype(str)
data_death['State']

<ipython-input-53-f87d53515dfb>:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data_death['State'] = data_death['State'].astype(str)

1        United States
2        United States
3        United States
4        United States
5        United States
             ...
14251      Puerto Rico
14252      Puerto Rico
14253      Puerto Rico
14254      Puerto Rico
14255      Puerto Rico
Name: State, Length: 14094, dtype: object

In [56]:
#data_vac 
data_vac['Location'] = data_vac['Location'].astype(str)
data_vac['Location']

0        NE
1        LA
2        GA
3        WY
4        CO
         ..
38483    AS
38484    VI
38485    MP
38486    US
38487    GU
Name: Location, Length: 38488, dtype: object